### PR TITLE
Fixes for the High Heels

### LINKED ISSUE #84: Cape clips body when wearing High Heels
Literally unplayable.

### PR DESCRIPTION
**Pull request by Mrbysco**
* Fixes #84 by also animating the humanoid model used by the cape layer
* Adds a data component capable of adjusting the entity dimensions when worn

### CODE REVIEW

File: src/main/java/com/lovetropics/extras/item/HighHeelsItem.java [hunk 1]
```diff
@@ -1,23 +1,72 @@
...
     public HighHeelsItem(Properties properties) {
         super(properties);
     }
 
+    @SubscribeEvent
+    public static void onEquip(LivingEquipmentChangeEvent event) {
+        LivingEntity livingEntity = event.getEntity();
+        if (event.getTo().has(ExtraDataComponents.ADJUST_HEIGHT) || event.getFrom().has(ExtraDataComponents.ADJUST_HEIGHT)) {
+            Pose pose = livingEntity.getPose();
+            livingEntity.setPose(Pose.CROUCHING); // Trigger size recalculation
```
Comment (Gegy) [inline src/main/java/com/lovetropics/extras/item/HighHeelsItem.java:40]: Would `livingEntity.refreshDimensions()` achieve the same thing? :)

**Review by Gegy — APPROVED** [review]

File: src/main/java/com/lovetropics/extras/item/HighHeelsItem.java (hunk 1 above)
Comment (Mrbysco) [reply src/main/java/com/lovetropics/extras/item/HighHeelsItem.java:40]: I originally had that, but the event only triggers server-side so nothing changed client-side

Comment (Mrbysco) [reply src/main/java/com/lovetropics/extras/item/HighHeelsItem.java:40]: I'm basically using the fact that poses are synced to the client to force an update

Comment (Gegy) [reply src/main/java/com/lovetropics/extras/item/HighHeelsItem.java:40]: Ohhh I see, that's sneaky :smile:
